version: '3.9'
services:
  cargodb:
    container_name: 'cargodb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=DevCargo'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
